### ISSUE TITLE
google search need enter a CAPTCHA

### ISSUE THREAD

**Issue by huwsun** [v2ray/v2ray-core#102]
prompt message:Our systems have detected unusual traffic from your computer network.

**Comment by v2ray** [comment]
This is a common issue when you tunnel through a VPS. The VPS provider may have many other users doing the same thing, which makes Google believe there is something unusual.

**Comment by hashhsah** [comment]
This occurs when v2ray::freedom connects to google from an IPv6 IP address.

Suggest adding an option to only use ipv4 in the freedom protocol.

**Comment by leowood2000** [comment]
The reason is All VPS from one provider are created with one IPv6 address, which is acquired by Stateless Address Autoconfiguration (SLAAC), and browers may use ipv6 address as first priority, so google may consider huge hit from one IPV6 address  is very suspicious,  I just request additional staic IPV6 pool from VPS porvider, and add one of static IPV6 addr then fix it. I still have my IPV6 address but not lease from SLAAC.  if you won't need IPV6, you can simply swtich off the IPV6 in your server, it also help solve this issues

**Comment by rufengsuixing** [comment]
/etc/gai.conf  add this

precedence ::ffff:0:0/96 100
