### ISSUE TITLE
StartInstance("json", jsondata)导致进程闪退

### ISSUE THREAD

**Issue by ameue** [v2ray/v2ray-core#1349]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.51
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过go get -u v2ray-core/core编译的core.framework
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
1、调用StartInstance("json", jsondata),返回错误Unable to load config in json
2、先调用RegisterConfigLoader(jsonConfigFormater)返回成功，再StartInstance("json", jsondata)，进程闪退在StartInstance-LoadConfig，如图：
<img width="343" alt="qq20181101-170923 2x" src="https://user-images.githubusercontent.com/10040900/47844619-c9fc0000-ddfd-11e8-95e7-1e5449e6b15d.png">

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by VictoriaRaymond** [comment]
请提供crash时的call stack

**Comment by FatChou** [comment]
<img width="984" alt="qq20181102-085244 2x" src="https://user-images.githubusercontent.com/10040900/47887928-cd829c00-de7c-11e8-8802-a4a56fb32a03.png">

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
