### ISSUE TITLE
support trojan protocol

### ISSUE THREAD

**Issue by Rucc1** [v2ray/v2ray-core#1404]
trojan project: https://github.com/trojan-gfw/trojan

trojan protocol specs: https://trojan-gfw.github.io/trojan/protocol

advantage: trojan protocol can __redirect__ illegal request to a web server or other backend services. 

this feature is like the one mentiond in issue: https://github.com/v2ray/Planning/issues/60

**Comment by VictoriaRaymond** [comment]
I don't think trojan "can redirect illegal request". It can only redirect when TLS handshake finishes and its own auth fails. It is equivalent to using WebSocket in V2Ray.

See https://trojan-gfw.github.io/trojan/protocol

> If the handshake succeeds, all subsequent traffic will be protected by TLS; otherwise, the server will close the connection immediately as any HTTPS server would.

**Comment by GreaterFire** [comment]
@VictoriaRaymond

Actually the point here is not that trojan "is equivalent to xxx". It is that the protocol gives v2ray the ability to control the redirection itself (instead of relying on nginx or other softwares) and gives you the freedom to redirect illegal connections to any service of your choice, like SMTP, IRC, and etc (not just those provided by nginx), and actually make use of them.

As the core author of trojan, I truly hope the protocol can be incorporated into v2ray.
