### ISSUE TITLE
功能请求：也集成udp2raw-tunnel那种 给UDP去掉udp头换上tcp头或者ICMP头的混淆方式用于增加抗QOS的手段

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#1416]
https://github.com/wangyu-/udp2raw-tunnel
说起来[当初](https://github.com/v2ray/v2ray-core/issues/235)是认为没有实现的可能
现在是@wangyu- 证实了这种可能性吧
V2的mkcp确实经常断

**Comment by VictoriaRaymond** [comment]
新协议必须有完整的协议文档，你需要有更加完整的说明来证明它的优点，并且说明它没有缺陷。

**Comment by daiaji** [comment]
@VictoriaRaymond 
把udp流量伪装成tcp /icmp

用raw socket给udp包加上tcp/icmp包头，可以突破udp流量限制或Udp QOS。或者在udp nat有问题的环境下，提升稳定性。  另外也支持用raw 发udp包，这样流量不会被伪装，只会被加密。

就是把mkcp的协议头改成TCP（在原先的预测中 貌似没人看好 但事实上ISP好像是用协议头QOS的）
mkcp不是说混淆也断流 用了这个的说没问题

https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/README.zh-cn.md

**Comment by VictoriaRaymond** [comment]
你需要了解一下TCP/IP的知识，如果识别成TCP那就真的是TCP流量了，不存在UDP被识别成TCP的情况。

**Comment by daiaji** [comment]
@VictoriaRaymond https://github.com/wangyu-/udp2raw-tunnel/wiki/faketcp%E6%96%B9%E6%A1%88%E5%92%8C%E5%B8%B8%E8%A7%81%E7%9A%84udp-over-tcp%E3%80%81udp-in-tcp%E6%96%B9%E6%A1%88%E7%9A%84%E5%8C%BA%E5%88%AB
这里 我是看不懂就是了

**Comment by Justsoos** [comment]
我没测过，但预估，内核之外改包头的 udp2raw 是相当耗费系统资源的。
如果要作，尽量有内核补丁支持才考虑。

实际上，用不着模拟 tcp 三次握手，就每个报改包头，用来欺骗网关设备就可行。
但kcp的发包算法，估计并没有同样即将成为http3 的 quic更健壮。
我倾向 quic 。毕竟，当全球厂商未来全面拥抱 http3 的时候，内核和网络里的【掩护流量】都让 quic 未来更有优势。
而且相应网关和路由也会对 quic 解除戒备。

另外，说个题外话，google 北京，上海多个服务器正式回归了。你们可以打开chrome，查看 quic 的洪流了。
包括如下域名：
```
update.googleapis.com
translate.googleapis.com
securepubads.g.doubleclick.net
adservice.google.co
adservice.google.com
update.googleapis.com
pagead2.googlesyndication.com
www.googletagservices.com
www.google-analytics.com
```

**Comment by Justsoos** [comment]
@wwqgtxx  我因为在这里盯着 google chrome 的开发 translate 修改，特别关注了，真正回归，是这个月才发生的，之前chrome内置翻译必须翻墙才能正确使用。甚至 co.jp 的 google 域名都被解析到国内了。 而且由于这个月大规模回归，终于可以看到墙内大量跑 quic 协议的包了。https://github.com/feliscatus/switchyomega/issues/264

另外，也不算没证据，有人用了udp2raw，在大流量下，系统资源耗费不是线性上升的，但当时没注意没留下链接。大致也在 udp2raw 的讨论下。路由器跑 kcp 有时候都会卡的，不要太迷信 udp。

另外，过网关设备实际就是本贴要提出v2ray要改的主要工作。背后的协议栈，我认为还是 quic 的会更成熟，尤其面对翻墙这种应用，在中美这样的长距离管道里。

**Comment by wwqgtxx** [comment]
相比udp2raw，kcptun本身的资源消耗要远大于udp2raw，kcptun的资源消耗别说在路由器这种低端设备上，就算是在x86机器上，cpu占用率也并不低，而且kcp协议的流控并不是完美的，他只是相比于tcp更加的激进。但是上述的问题都和udp2raw本身没啥关系，在v2ray的应用中，udp2raw是应该作为mkcp或者quic的承载层，并不需要用kcptun再套一层，多此一举。至于大流量下的资源占用不是线性上升，那是必然的，就算是内核的tcp栈在面对高并发的时候资源占用也不是线性上升的，作为一个规模不算大的用户态程序能做到这样的效率已经很不容易了。发自我的iPhone------------------ 原始邮件 ------------------发件人: Justsoos  <notifications@github.com>发送时间: 2018年11月25日 18:57收件人: v2ray/v2ray-core <v2ray-core@noreply.github.com>抄送: wwqgtxx <wwqgtxx@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[v2ray/v2ray-core] 功能请求：也集成udp2raw-tunnel那种 给UDP去掉udp头换上tcp头或者ICMP头的混淆方式用于增加抗QOS的手段 (#1416)@wwqgtxx  我因为在这里盯着 google chrome 的开发 translate 修改，特别关注了，真正回归，是这个月才发生的，之前chrome内置翻译必须翻墙才能正确使用。甚至 co.jp 的 google 域名都被解析到国内了。 而且由于这个月大规模回归，终于可以看到墙内大量跑 quic 协议的包了。FelisCatus/SwitchyOmega#264
另外，也不算没证据，有人用了udp2raw，在大流量下，系统资源耗费不是线性上升的，但当时没注意没留下链接。大致也在 udp2raw 的讨论下。路由器跑 kcp 有时候都会卡的，不要太迷信 udp。
另外，过网关设备实际就是本贴要提出v2ray要改的主要工作。背后的协议栈，我认为还是 quic 的会更成熟，尤其面对翻墙这种应用，在中美这样的长距离管道里。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v2ray/v2ray-core","title":"v2ray/v2ray-core","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/v2ray/v2ray-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Justsoos in #1416: @wwqgtxx  我因为在这里盯着 google chrome 的开发 translate 修改，特别关注了，真正回归，是这个月才发生的，之前chrome内置翻译必须翻墙才能正确使用。甚至 co.jp 的 google 域名都被解析到国内了。 而且由于这个月大规模回归，终于可以看到墙内大量跑 quic 协议的包了。https://github.com/feliscatus/switchyomega/issues/264\r\n\r\n另外，也不算没证据，有人用了udp2raw，在大流量下，系统资源耗费不是线性上升的，但当时没注意没留下链接。大致也在 udp2raw 的讨论下。路由器跑 kcp 有时候都会卡的，不要太迷信 udp。\r\n\r\n另外，过网关设备实际就是本贴要提出v2ray要改的主要工作。背后的协议栈，我认为还是 quic 的会更成熟，尤其面对翻墙这种应用，在中美这样的长距离管道里。\r\n"}],"action":{"name":"View Issue","url":"https://github.com/v2ray/v2ray-core/issues/1416#issuecomment-441431690"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/v2ray/v2ray-core/issues/1416#issuecomment-441431690",
"url": "https://github.com/v2ray/v2ray-core/issues/1416#issuecomment-441431690",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [v2ray/v2ray-core] 功能请求：也集成udp2raw-tunnel那种 给UDP去掉udp头换上tcp头或者ICMP头的混淆方式用于增加抗QOS的手段 (#1416)",
"sections": [
{
"text": "",
"activityTitle": "**Justsoos**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Justsoos",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"v2ray/v2ray-core\",\n\"issueId\": 1416,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/v2ray/v2ray-core/issues/1416#issuecomment-441431690"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 412953953\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Justsoos** [comment]
嗯，很久前在csdn上看到有人用raw socket测过改包，对系统压力极大，接近指数曲线，看过后来就没关注过这种用户级别的改包。谁有空可以测测。要说在NAT上开个口，其实不难，不用模拟tcp三次握手，每次连接前做个对话就行了，而且由于是假的 tcp 连接，不介意可以在 nat 网关上面多开几个口，把并发传输都加上去，这样就更好玩了。

**Comment by wwqgtxx** [comment]
@daiaji 不是你这个意思，是udp2raw作为底层的协议替代mkcp底层的udp，你要搞清楚协议的分层问题

**Comment by PHCSJC** [comment]
好吧，没想到在这里看到这个讨论了，今天特地测试了v2ray+udp2raw。
初始结论是：
1.可以运行，没有问题。
2.v2ray替换掉了kcptun和ss，替换后在看视频时v2ray的CPU占用率明显比kcptun要低。
3.延时还没有特别的感觉，因为kcptun+udp2raw的延时已经非常低了。v2ray+udp2raw的延时同样非常低，网页都是瞬间打开的。

**Comment by GeonChen** [comment]
在Vmess协议Outbound设置kcp传输并设header里type为none，直接串联udp2raw即可。

**Comment by pinatsu** [comment]
> 好吧，没想到在这里看到这个讨论了，今天特地测试了v2ray+udp2raw。
> 初步结论是：
> 1.可以运行，没有问题。v2ray的传输协议使用的是mkcp
> 2.v2ray替换掉了kcptun和ss，替换后在看视频时v2ray的CPU占用率明显比kcptun要低，说明v2ray在kcp上的实现比kcptun要节省资源。
> 3.延时还没有特别的感觉，因为kcptun+udp2raw的延时已经非常低了。v2ray+udp2raw的延时同样非常低，网页都是瞬间打开的。

请问v2ray+udp2raw是怎么操作的
