### ISSUE TITLE
v2可否加入一个双向通道的功能？用来伪装p2p下载软件的回程流量

### ISSUE THREAD

**Issue by wutongskype** [v2ray/v2ray-core#1422]
我的目的是用v2代理本地的下载软件，并且伪装服务器转发回本地客户端的流量。

一般情况下使用v2代理本地p2p下载软件时大概是这种情况：客户机 vmess to 服务器，客户端这边设置p2p软件走本地v2的s5端口。从而走而客户端到服务器的vmess通道，服务器那边用v2任意门功能把自己的一个端口转发回本地路由器（路由器设置动态域名）。

那么问题就是，此时从服务器用任意门功能转发回本地的流量，应该是原始的吧？如果是p2p软件的下载流量应该会被运营商识别吧？识别之后各种ooxx各种QQooss。有办法也给他伪装成其他流量吗？比如客户端这边在开一个ws+tls的in口，服务器那边另外添加一个out口与客户端建立一条ws tls通道，用v2内置路由功能让用任意门转发回本地的p2p流量套到这个服务器到客户端的tls通道里？

感觉这样设置很蠢😂

**Comment by 2810676203** [comment]
你在说啥 😂

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
