### ISSUE TITLE
mkcp不能完全过滤bt协议。路由中禁止了bt，但bt还会默认走第一个outbound

### ISSUE THREAD

**Issue by cjjdaq** [v2ray/v2ray-core#1474]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.9
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不能完全顾虑掉bt协议。tcp正常，udp依然跑流量。比如使用mkcp，本地下载bt依然会有一部分流量走v2代理。tcp的几个协议则没有此问题。
4) 你期待看到的正确表现是怎样的？
udp类的协议能正常过滤bt协议
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
略
服务器端配置:

略

客户端配置:

略

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

略

客户端错误日志:

略

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

略

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by caonimac** [comment]
能分享一下不代理iptables规则吗？昨天pt跑掉了200G。谢谢。

**Comment by Cwek** [comment]
有错字，连配置文件都略略略，别人怎么帮你看啊。
inbound要打开sniffing功能，路由中设置至少设置一项的"protocol":["bittorrent"]指向outbound的blankhole。

**Comment by kslr** [comment]
你需要提供配置信息，传输日志，以及如何判断下载器没有被绕过

**Comment by liberal-boy** [comment]
请提供配置文件。
过滤bt与mkcp有何关系？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
