### ISSUE TITLE
How to generate qr-code from config.json?

### ISSUE THREAD

**Issue by LinArcX** [v2ray/v2ray-core#1691]
Hi. i'm using v2ray in linux without any issue, but for android, you may manually enter all configurations. it's a pain..
It'll be good to export config.json to qr-code and import it in android client.

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/1645

**Comment by Xyncgas** [comment]
external api

**Comment by Xyncgas** [comment]
I mean there are open  source qr code endcoder out there, and it's not even that hard to make one, so as long as you can download a qr code reader for text from the google store, you can now already dump the configuration file to the encoder, and put it anywhere on the wall, and then let people scan it on their phone, and then just copy it

**Comment by Xyncgas** [comment]
Although when we talk about scanning the qr code, we need to know that this is an open source program that basically give freedom to the internet users at its core, not being able to see the content if when you just let the v2ray to use it is dangerous
  that takes away the freedom from user, hell how many people do you even think would become a programer if we start forcing ourselves to have the obligation to make every computing language to be high level and easy to use, but it's them who needs to learn the simple truth the computing languages and make their life better by using it and we don't have the obligation to spoon feed people so they can scan a QR code and use the program. And think about the freedom you are taking away from user when QR code is directly tied to the v2ray and deployed in scale, that can make governments to be able to exploit the people using the program much easier than ever before as well, by just switching the QR codes with the one that has a honey pod address and weak encryption in some public channel.
  I think with the current QR code readers out there you could already make it convienient for yourself to encode your config to qr code and then decode it anytime. But imagine embedding this function into the v2ray core is like letting people to scan random malicious config on the street, and traditionally we give out settings to users through the vendors' website like how you buy a vpn and you get an account and password or if you buy an ssr you get a server address and the port and password .... etc, basically is like that, or maybe there are some public ssr servers out there that shares the server ip and stuff something like that, if you were to scan a QR code on the website after buying it, you would have to open the QR code reader then you scan the QR code and you get the configuration file then you copy it to the core, while if you do inject the QR code module into v2ray then on your phone you would use it instead to scan the QR code provided then let the core use it, that's uninformative and inconvenient, because you don't know what you are getting, while with plain text you just need to copy it then paste it to v2ray, easy.
  And imagine people scanning random QR codes out in the open to get the configuration for the core, well somebody will come up with encrypting the configuration file one day and BOOM you make v2ray into a virus a epidemic that serve more to the conspiring nature of the communist party in china and less in the interest of the users of freedom.

**Comment by nicholascw** [comment]
irrelevant with the project’s goal.

**Comment by agn-7** [comment]
@LinArcX  Did you find an approach to convert a V2ray config to vmess address or QRcode?

**Comment by mirhmousavi** [comment]
I ended up exporting the configuration from V2rayNG. there's no online website or tool that does it
