### ISSUE TITLE
服务器端systemctl start v2ray启动失败(code=exited, status=255)

### ISSUE THREAD

**Issue by aWhver** [v2ray/v2ray-core#2022]
1、使用的v2ray是版本为4.21.3
2、使用场景？
      最近shadowsocks丢包严重，尝试使用v2ray,首次配置
3、根据官方文档配置最简单的版本启动失败
服务端配置：
```javascript
{
  "inbounds": [
    {
      "port": 52726,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "86b8ba5a-f9b3-4989-8afd-54196e46e74c",
            "alterId": 64
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```
客户端配置：
```javascript
{
  "inbounds": [
    {
      "port": 1081,
      "protocol": "socks",
      "settings": {
        "auth": "noauth"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxxx.xx",
            "port": 52726,
            "users": [
              {
                "id": "86b8ba5a-f9b3-4989-8afd-54196e46e74c",
                "alterId": 64
              }
            ]
          }
        ]
      }
    }
  ]
}
```
启动报错：
```javascript
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 六 2019-11-09 09:54:48 EST; 16min ago
  Process: 3915 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 3915 (code=exited, status=255)

11月 09 09:54:48 host.localdomain systemd[1]: v2ray.service: main process exited, code.../a
11月 09 09:54:48 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 09 09:54:48 host.localdomain systemd[1]: v2ray.service failed.
11月 09 09:54:48 host.localdomain systemd[1]: v2ray.service holdoff time over, schedul...t.
11月 09 09:54:48 host.localdomain systemd[1]: start request repeated too quickly for v...ce
11月 09 09:54:48 host.localdomain systemd[1]: Failed to start V2Ray Service.
11月 09 09:54:48 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 09 09:54:48 host.localdomain systemd[1]: v2ray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

使用了`**/usr/bin/v2ray/v2ray test -config /etc/v2ray/config.json**`测试配置是对的
提示如下：
![image](https://user-images.githubusercontent.com/27797395/68530935-07b43280-0348-11ea-8a50-c0604cc6e644.png)

4、journalctl -u v2ray 日志
```javascript
11月 07 07:53:47 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 07:53:47 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 07:53:47 host.localdomain v2ray[1780]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 07:53:47 host.localdomain v2ray[1780]: A unified platform for anti-censorship.
11月 07 07:53:48 host.localdomain v2ray[1780]: 2019/11/07 07:53:48 [Warning] v2ray.com/core: V2Ray 4.21.3 started
11月 07 19:48:01 host.localdomain systemd[1]: Stopping V2Ray Service...
11月 07 19:48:01 host.localdomain systemd[1]: Stopped V2Ray Service.
11月 07 19:59:37 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 19:59:37 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 19:59:37 host.localdomain v2ray[2407]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 19:59:37 host.localdomain v2ray[2407]: A unified platform for anti-censorship.
11月 07 19:59:37 host.localdomain v2ray[2407]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726 > v2ray.com/core/transport/internet: failed to
11月 07 19:59:37 host.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
11月 07 19:59:37 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 07 19:59:37 host.localdomain systemd[1]: v2ray.service failed.
11月 07 19:59:37 host.localdomain systemd[1]: v2ray.service holdoff time over, scheduling restart.
11月 07 19:59:37 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 19:59:37 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 19:59:37 host.localdomain v2ray[2419]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 19:59:37 host.localdomain v2ray[2419]: A unified platform for anti-censorship.
11月 07 19:59:37 host.localdomain v2ray[2419]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726 > v2ray.com/core/transport/internet: failed to
11月 07 19:59:37 host.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
11月 07 19:59:37 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 07 19:59:37 host.localdomain systemd[1]: v2ray.service failed.
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service holdoff time over, scheduling restart.
11月 07 19:59:38 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 19:59:38 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 19:59:38 host.localdomain v2ray[2431]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 19:59:38 host.localdomain v2ray[2431]: A unified platform for anti-censorship.
11月 07 19:59:38 host.localdomain v2ray[2431]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726 > v2ray.com/core/transport/internet: failed to
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
11月 07 19:59:38 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service failed.
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service holdoff time over, scheduling restart.
11月 07 19:59:38 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 19:59:38 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 19:59:38 host.localdomain v2ray[2442]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 19:59:38 host.localdomain v2ray[2442]: A unified platform for anti-censorship.
11月 07 19:59:38 host.localdomain v2ray[2442]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726 > v2ray.com/core/transport/internet: failed to
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
11月 07 19:59:38 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service failed.
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service holdoff time over, scheduling restart.
11月 07 19:59:38 host.localdomain systemd[1]: Started V2Ray Service.
11月 07 19:59:38 host.localdomain systemd[1]: Starting V2Ray Service...
11月 07 19:59:38 host.localdomain v2ray[2453]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
11月 07 19:59:38 host.localdomain v2ray[2453]: A unified platform for anti-censorship.
11月 07 19:59:38 host.localdomain v2ray[2453]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726 > v2ray.com/core/transport/internet: failed to
11月 07 19:59:38 host.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
11月 07 19:59:38 host.localdomain systemd[1]: Unit v2ray.service entered failed state.
```

**Comment by kingwilliam** [comment]
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726

伺服器 tcp 52726, 会否已给其他服务使用?

**Comment by aWhver** [comment]
> Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 52726
> 
> 伺服器 tcp 52726, 会否已给其他服务使用?

没有，我就一个服务器，不过我的shadowsocks没有关，应该没关系的吧

**Comment by kingwilliam** [comment]
或将52726转其他试试

**Comment by aWhver** [comment]
> 或将52726转其他试试

我转了另一个端口，但还是一样的错误：
```javascript
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 32695
```

**Comment by kingwilliam** [comment]
是用root或有root权限吗？感觉您的v2ray不够权限.

**Comment by aWhver** [comment]
> 是用root或有root权限吗？感觉您的v2ray不够权限.

v2ray权限不够？不太明白。看网上的很多配了nginx、tsl。我都没有，和这有关系吗

**Comment by ileeoyo** [comment]
感觉你journalctl日志复制的不全，journalctl日志可以左右键滚动查看的。无法启动的原因一般都在这个日志里写的很清楚

**Comment by jellycsc** [comment]
试试运行 `/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json` 看是什么报错

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/blob/master/release/config/systemd/v2ray.service

**Comment by KevinRSX** [comment]
像楼上说的一样试下`/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json`是什么报错，如果是端口被占用的话先stop并且disable service再`sudo lsof -i -P -n | grep INBOUND_PORT`把所有占用了端口的进程kill掉就行了

**Comment by superb24ED** [comment]
把/user/bin/v2ray/v2ray改成/usr/bin/v2ray

**Comment by xiefeiphil** [comment]
我遇到相同的问题。原因是shadowsocks的加密协议开始选择为：aes-256-cfb，改回chacha20-ietf-poly1305后就正常了。

**Comment by phyzhenli** [comment]
> 我遇到相同的问题。原因是shadowsocks的加密协议开始选择为：aes-256-cfb，改回chacha20-ietf-poly1305后就正常了。

我也遇到了相同的问题，目前我用的是最新的4.42.2版本，发现已经不支持aes-256-cfb的加密方式了。

**Comment by jqu003** [comment]
各位我遇到了类似的问题，打印如下，请教下可能是什么原因？

[root@localhost tmp]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2022-05-28 11:27:03 CST; 4s ago
     Docs: https://www.v2fly.org/
  Process: 74905 ExecStart=/usr/bin/v2ray -config /etc/v2ray/config.json (code=exited, status=203/EXEC)
 Main PID: 74905 (code=exited, status=203/EXEC)

May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.
May 28 11:27:03 localhost systemd[1]: v2ray.service holdoff time over, scheduling restart.
May 28 11:27:03 localhost systemd[1]: start request repeated too quickly for v2ray.service
May 28 11:27:03 localhost systemd[1]: Failed to start V2Ray Service.
May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.

**Comment by jqu003** [comment]
各位我遇到了类似的问题，打印如下，请教x是什么原因？

[root@localhost tmp]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2022-05-28 11:27:03 CST; 4s ago
     Docs: https://www.v2fly.org/
  Process: 74905 ExecStart=/usr/bin/v2ray -config /etc/v2ray/config.json (code=exited, status=203/EXEC)
 Main PID: 74905 (code=exited, status=203/EXEC)

May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.
May 28 11:27:03 localhost systemd[1]: v2ray.service holdoff time over, scheduling restart.
May 28 11:27:03 localhost systemd[1]: start request repeated too quickly for v2ray.service
May 28 11:27:03 localhost systemd[1]: Failed to start V2Ray Service.
May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.

**Comment by jqu003** [comment]
各位我遇到了类似的问题，打印如下，请问是什么原因？

[root@localhost tmp]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2022-05-28 11:27:03 CST; 4s ago
     Docs: https://www.v2fly.org/
  Process: 74905 ExecStart=/usr/bin/v2ray -config /etc/v2ray/config.json (code=exited, status=203/EXEC)
 Main PID: 74905 (code=exited, status=203/EXEC)

May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.
May 28 11:27:03 localhost systemd[1]: v2ray.service holdoff time over, scheduling restart.
May 28 11:27:03 localhost systemd[1]: start request repeated too quickly for v2ray.service
May 28 11:27:03 localhost systemd[1]: Failed to start V2Ray Service.
May 28 11:27:03 localhost systemd[1]: Unit v2ray.service entered failed state.
May 28 11:27:03 localhost systemd[1]: v2ray.service failed.

**Comment by aohanhongzhi** [comment]
客户端遇到启动不了的问题了。sudo下就可以启动，但是service里就启动不了
![image](https://github.com/v2ray/v2ray-core/assets/37319319/b5fa8a56-8c56-4fee-b252-0724b90eaaf1)

**Comment by kingwilliam** [comment]
> 客户端遇到启动不了的问题了。sudo下就可以启动，但是service里就启动不了 ![image](https://private-user-images.githubusercontent.com/37319319/296221162-b5fa8a56-8c56-4fee-b252-0724b90eaaf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTkwNzEsIm5iZiI6MTcwNTA1ODc3MSwicGF0aCI6Ii8zNzMxOTMxOS8yOTYyMjExNjItYjVmYThhNTYtOGM1Ni00ZmVlLWIyNTItMDcyNGI5MGVhYWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDExMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjZlMDkyNGIwOGNlZGUzMDVlY2EwZmY2MTE4OWI2Y2Y0MDAyZmRmODJmNjcyZmQ1MmY5ZDVhMWQ5YWUxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbJjQGbCvpSant1OQ---IVkCdK-G20u0MpUtcr8WfGY)

您留意看看 loyalsoldiersite.dat 阅读权限

**Comment by aohanhongzhi** [comment]
可以查看下日志
```shell
sudo journalctl -xe | grep v2ray
```

**Comment by aohanhongzhi** [comment]
> > 客户端遇到启动不了的问题了。sudo下就可以启动，但是service里就启动不了 ![image](https://private-user-images.githubusercontent.com/37319319/296221162-b5fa8a56-8c56-4fee-b252-0724b90eaaf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTkwNzEsIm5iZiI6MTcwNTA1ODc3MSwicGF0aCI6Ii8zNzMxOTMxOS8yOTYyMjExNjItYjVmYThhNTYtOGM1Ni00ZmVlLWIyNTItMDcyNGI5MGVhYWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDExMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjZlMDkyNGIwOGNlZGUzMDVlY2EwZmY2MTE4OWI2Y2Y0MDAyZmRmODJmNjcyZmQ1MmY5ZDVhMWQ5YWUxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbJjQGbCvpSant1OQ---IVkCdK-G20u0MpUtcr8WfGY)
> 
> 您留意看看 loyalsoldiersite.dat 阅读权限

我通过
```shell
sudo journalctl -xe | grep v2ray
``` 


分析确实因为 loyalsoldiersite.dat文件不存在，我直接在config.json文件中移除了 loyalsoldiersite.dat就可以了。
