### ISSUE TITLE
Non-RFC1928 compliant SOCKS5 client implementation

### ISSUE THREAD

**Issue by uno20001** [v2ray/v2ray-core#2179]
As per my understanding of [RFC 1928](https://tools.ietf.org/html/rfc1928), the following handshake is required when connecting to a SOCKS5 server:
 * client -> server: SOCKS version + supported authentication methods
 * server -> client: selected method
 * client <-> server: method dependent negotiation
 * client -> server: SOCKS request
 * server -> client: SOCKS reply

The current implementation of this handshake in *v2ray-core* ([here](https://github.com/v2ray/v2ray-core/blob/5dd85717fcbc2f6b2175c6e9e258e8e964c0d0d3/proxy/socks/protocol.go#L393)) does not wait for the server to indicate which authentication method the server wants to use, it sends the username/password authentication related data along the version identifier/method selection message. This, in my opinion, makes *v2ray-core* non-RFC compliant (when username/password authentication is enabled), but my interpretation might be wrong, so I would like to hear the inputs of authors and contributors. Furthermore, the fact that most SOCKS5 client implementations act according to my interpretation makes me think that that is the expected behaviour ([curl](https://github.com/curl/curl/blob/f128c00a99ffb7482740f3579f42f5e026a1ee74/lib/socks.c#L354), [dante](https://github.com/notpeter/dante/blob/490f343af585a9be345cd775bf2569b21bc5fdf7/dante/lib/authneg.c#L51), [gosocks5](https://github.com/ginuerzh/gosocks5/blob/master/conn.go#L65) - *used in [gost](https://github.com/ginuerzh/gost)*, etc.)

**Comment by Tai7sy** [comment]
This will make handshake faster.
Since tcp is streaming, there is no difference between sending version identifier and auth data in one time and two.

But this behavior will cause some problem indeed when the implementation of socks5 server was bad.
for example, the first recv exceeds the length it should have (like "recv(s, 255)", I have seen this before). but in this case, its the problem of the server, not the client.
