### ISSUE TITLE
谷歌搜索的时候让输入验证码

### ISSUE THREAD

**Issue by Jason4774** [v2ray/v2ray-core#264]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.1.2windows版
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
谷歌搜索
3) 你看到的不正常的现象是什么？
3) What did you see?
谷歌搜索的时候让输入验证码
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
没有让输入验证码的提示
5) 请附上你的配置文件。
5) Please attach your configuration file.
未做修改的配置文件
![qq 20160922154339](https://cloud.githubusercontent.com/assets/19594338/18740331/cb5919c8-80db-11e6-8130-f42bb4c0aec4.png)

PS:我不知道是不是和v2ray有关，我结合了meow使用，请问这个改怎么解决？谢谢。

**Comment by cnperi** [comment]
应该是你的VPS到Google服务器走的是ipv6通道造成的。
把VPS的ipv6关闭，走ipv4就好了。

**Comment by Jason4774** [comment]
谢谢，也不是经常出现这种情况，只是不知道原因，我使用的是v2ray，我改怎么修改啊？

**Comment by wtlusvm** [comment]
@Jason4774 无法修改。Google识别你VPS的IP地址段爬虫较多所以加了限制。

话说vultr也进入Google的名单上了么，忧伤。

最后的忠告，下次贴图记得隐藏IP地址

**Comment by v2ray** [comment]
通常是 IP 的问题，更换 IP 或许可以解决。

**Comment by leowood2000** [comment]
The reason is All VPS from one provider are created with one IPv6 address, which is acquired by Stateless Address Autoconfiguration (SLAAC), and browers may use ipv6 address as first priority, so google may consider huge hit from one IPV6 address  is very suspicious,  I just request additional staic IPV6 pool from VPS porvider, and add one of static IPV6 addr then fix it. I still have my IPV6 address but not lease from SLAAC.  if you won't need IPV6, you can simply swtich off the IPV6 in your server, it also help solve this issues

**Comment by rufengsuixing** [comment]
#102

**Comment by TheresaWChavez789** [comment]
ok
