### ISSUE TITLE
HTTP Client: Performance Issues

### ISSUE THREAD

**Issue by Anonymous-Someneese** [v2ray/v2ray-core#2721]
I am currently using http+tls for proxy but found several problems in current HTTP tunnel implementation:

- Unknown reason for using HTTP/2 for CONNECT method
This would introduce head-of-line block delay if http2 reuse are in place. Since some streams might be used for video streaming, it can increase delay significantly.

- 0RTT commit blocks connections without initial data (d05ddc8f78d)
- coarse mutex cachedH2Mutex serialize Dispatch function (http/client.go)

I would like to issue a pull request but do you have any consideration on this?

**Comment by darhwa** [comment]
> HTTP/2 for CONNECT method

HTTP/2 is default but not mandatory. `{"h2", "http/1.1"}` was chosen as the default alpn because mainstream browsers all do that. If one really don't like h2 one can customize `alpn` under `tlsSettings`. And about performance, we need numbers.

> 0RTT commit blocks connections without initial data (d05ddc8)

Can you give an example of application setting up a connection without sending the first payload immediately?

> coarse mutex cachedH2Mutex serialize Dispatch function (http/client.go)

I agree that this lacks of consideration.
