### ISSUE TITLE
how to change v2ray chinasite list?

### ISSUE THREAD

**Issue by gggin** [v2ray/v2ray-core#278]
Can I set url by config.json file?

**Comment by v2ray** [comment]
Please contribute new sites to [this file](https://github.com/v2ray/v2ray-core/blob/master/tools/conf/router_chinasites.go), so that every V2Ray user will be benefit from the next release. In the meantime, you may add a '[field](https://www.v2ray.com/chapter_02/03_routing.html#field)' rule in your routing config.
