### ISSUE TITLE
服务器有多个IP时，如何设置能随机使用其中的IP

### ISSUE THREAD

**Issue by s0l0m0nc** [v2ray/v2ray-core#463]
1)  你正在使用哪个版本的 V2Ray？
2.31
2)  你的使用场景是什么？
目前有一服务器有多个IP：如1.1.1.1，2.2.2.2。所有用户通过1.1.1.1连入v2ray，但出口能随机使用1.1.1.1,2.2.2.2

**Comment by konbar** [comment]
1、v2ray-v2.31-windows-64版本，无法访问油管等网站，连GG都不能访问，最早的v2ray-v2.20.2-windows-64早期可以用，这后来也是用不了了。
2、我主要用google浏览器配合switchyOmega搭载SS或者SSR高速观看油管等圭寸锁的网站。
我不是服务器，只是私人访问者。原来手机与电脑都能访问，现在一个都不能访问油管这引起网站了。

------------------ 原始邮件 ------------------
*发件人:* "s0l0m0nc";<notifications@github.com>;
*发送时间:* 2017年6月6日(星期二) 中午1:08
*收件人:* "v2ray/v2ray-core"<v2ray-core@noreply.github.com>;
*抄送:* "Subscribed"<subscribed@noreply.github.com>;
*主题:* [v2ray/v2ray-core] 服务器有多个IP时，如何设置能随机使用其中的IP (#463)

提交 Issue 之前请先阅读 Issue 指引 <https://www.v2ray.com/zh_cn/chapter_01/issue.html>
，然后回答下面的问题，谢谢。
Please read the instruction
<https://www.v2ray.com/en/get_started/issue.html> and answer the following
questions before submitting your issue. Thank you.

   1. 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
   What version of V2Ray are you using (If you deploy different version on
   server and client, please explicitly point out)?
   2.31
   2. 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
   What's your scenario of using V2Ray? E.g., Watching YouTube videos in
   Chrome via Socks/VMess proxy.

   目前有一服务器有多个IP：如1.1.1.1，2.2.2.2。所有用户通过1.1.1.1连入v2ray，但出口能随机使用1.1.1.1,2.2.2.2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/v2ray/v2ray-core/issues/463>, or mute the thread

**Comment by DarienRaymond** [comment]
@s0l0m0nc 这个是Golang的行为，[文档上](https://golang.org/pkg/net/#Dialer)没有说是随机选择还是确定算法。如果Golang不是随机选的，V2Ray也暂时不会提供随机选择的方式。

@konbar 如果你有任何问题，请单独开一个issue讨论。

**Comment by konbar** [comment]
已明白你的意思，有空的时候我会多关注v2ray/v2rag-core!

QQ邮箱可以收到你的邮件，但是发不出邮件给你，只有搭载SS用GMAIL邮箱给你回信。。。

------------------ 原始邮件 ------------------
*发件人:* "DarienRaymond";<notifications@github.com>;
*发送时间:* 2017年6月6日(星期二) 下午5:10
*收件人:* "v2ray/v2ray-core"<v2ray-core@noreply.github.com>;
*抄送:* "konbar"<13087685@qq.com>; "Mention"<mention@noreply.github.com>;
*主题:* Re: [v2ray/v2ray-core] 服务器有多个IP时，如何设置能随机使用其中的IP (#463)

@s0l0m0nc <https://github.com/s0l0m0nc> 这个是Golang的行为，文档上
<https://golang.org/pkg/net/#Dialer>
没有说是随机选择还是确定算法。如果Golang不是随机选的，V2Ray也暂时不会提供随机选择的方式。

@konbar <https://github.com/konbar> 如果你有任何问题，请单独开一个issue讨论。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/v2ray/v2ray-core/issues/463#issuecomment-306427724>,
or mute
the thread
