### ISSUE TITLE
Enable selective routing

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#49]
V2Ray should provide an interface to route traffic on demand.

**Comment by v2ray** [comment]
Selective routing will be provided in V1.0

**Comment by sign4bill** [comment]
To access blocked sites effectively, two basic selective routing methods should be provided:

1. Use proxy only for non-China IP, [goproxy](https://github.com/shell909090/goproxy) provided this strategy. A reliable DNS lookup result should be provided if use this method. 
2. Use proxy only for gfwlist url, [cow](https://github.com/cyfdecyf/cow) provided this strategy. The blocked url list should be provided dynamically.

## Pros and Cons

1. Method 1: A static strategy. Easy to implement, but hard to get reliable DNS lookup results, and route all the traffic outside China maybe slow for some sites.
2. Method 2: A dynamic way to identify blocked sites, more effective in the most cases. People in the university cannot use the method1 because you can access some scholar databases sites with the university IP only.

**Comment by v2ray** [comment]
Static routing is implemented. Users may now add IP and/or domain for bypassing. Dynamic routing will be planned later.
