### ISSUE TITLE
Support chacha20 in Shadowsocks protocol

### ISSUE THREAD

**Issue by Sherman-Liu** [v2ray/v2ray-core#95]
First of all, please allow me to say thank you to all you contributors, you're the people who's really changing the world.

Here's my question, is there going to be more encryption methods in the embedded Shadowsocks protocol for our users to choose?

I know that AES-128/AES-256 could be super strong in security, but they are not very 'mobile friendly', they used up a lot of resources on the phone and drain the battery quickly, maybe something like chacha20 could be more efficient?

People always say 'if it ain't broke, don't fix it', so I wouldn't be too surprised if your answer is 'no', but I hope there'll be some changes in the future.

Best wishes!

**Comment by v2ray** [comment]
Chacha20 is not supported for now simply because Golang doesn't support it officially. I am looking for a third-party implementation. It gonna take some time.

Please also notice that, chacha20 is only suitable for mobile phones. It has no advantage on devices with AES NI enabled. Chacha20 consumes more energy than AES on a x86 CPU with AES NI.

**Comment by Sherman-Liu** [comment]
Thank you for the explanation.

**Comment by v2ray** [comment]
ChaCha20 and ChaCha20-IETF will be enabled in V2Ray 1.9.

**Comment by Sherman-Liu** [comment]
That is…next version?

Wow, stunningly quick!

Great job!
